[package]
name = "brilliant-CV"
version = "2.0.0"
entrypoint = "lib.typ"
authors = ["Yunan Wang <https://github.com/mintyfrankie>"]
license = "Apache-2.0"
description = "💼 another CV template for your job application, yet powered by Typst and more"
repository = "https://github.com/mintyfrankie/brilliant-CV"
keywords = ["cv", "resume", "cover-letter", "curriculum-vitae", "modular", "multilingual", "ai-injection"]
categories = ["cv", "languages", "layout", "components"]
compiler = "0.11.1"
# exclude = 

[template]
path = "template"
entrypoint = "cv.typ"
# thumbnail = "assets/images/resume.png"