name: Generate Documentation

on:
  push: {}

jobs:
  build:
    name: build-docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        id: setup-typst

      - run: typst compile docs.typ

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./*.pdf
          if-no-files-found: error

  deploy:
    name: deploy-docs
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.build.outputs.page-url }}

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: documentation
      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v4
