name: Generate Documentation

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: compile-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        id: setup-typst

      - run: typst compile docs.typ

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./*.pdf
          if-no-files-found: error
