name: Release

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches:
      - feat-v2.1.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
  